using DayCare_ManagementSystem_API.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Driver;
using DayCare_ManagementSystem_API.Helper;
using DayCare_ManagementSystem_API.Models;
using DayCare_ManagementSystem_API.Models.DTOs;
using System.Security.Claims;
using DayCare_ManagementSystem_API.Service;

namespace DayCare_ManagementSystem_API.Controllers
{
    [Authorize]
    [Route("api/users")]
    [ApiController]
    public class UsersController : ControllerBase
    {
        private readonly ILogger<UsersController> _logger;
        private readonly IUser _userRepo;
        private readonly PasswordHelper _passwordHelper;
        private readonly EmailService _emailService;

        public UsersController(ILogger<UsersController> logger, IUser userRepo, PasswordHelper passwordHelper, EmailService emailService)
        {
            _logger = logger;
            _userRepo = userRepo;
            _passwordHelper = passwordHelper;
            _emailService = emailService;
        }

        #region [ Me ]
        [HttpGet("me")]
        public async Task<ActionResult<UserDTO>> Me()
        {
            try
            {
                var tokenType = User.Claims.FirstOrDefault(c => c.Type == "TokenType")?.Value;
                var tokenUserId = User?.FindFirstValue(ClaimTypes.Sid)?.ToString();

                if (tokenType != "access-token")
                {
                    return Unauthorized(new { Message = "Invalid token" });
                }

                var user = await _userRepo.GetUserById(tokenUserId);

                if (user == null)
                {
                    return NotFound(new { Message = "User does not exist" });
                }

                var Credentials = new Credentials()
                {
                    Email = user.Email,
                    Firstname = user.Firstname,
                    Lastname = user.Lastname,
                    Role = user.Role,
                    Id = user.Id,
                    isMFAEnabled = user.isMFAEnabled
                };

                return Ok(Credentials);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error in the Users Controller while trying to get user by id.");
                return StatusCode(500, new { Message = "Encountered an error" });
            }
        }
        #endregion

        #region [ Add Staff ]
        [Authorize(Roles = "admin")]
        [HttpPost("add-staff")]
        public async Task<ActionResult> AddStaff(AddStaff request)
        {

            try
            {
                var roles = new List<string>() { "staff", "admin", "guardian" };

                var userExists = await _userRepo.GetUserByEmail(request.Email);

                if (userExists != null)
                {
                    return Conflict(new { Message = "User already exists" });
                }

                if (!roles.Contains(request.Role.ToLower()))
                {
                    return BadRequest(new { Message = "Invalid role" });
                }

                string autoGeneratedPassword = _passwordHelper.GenerateRandomPassword();

                User user = new User
                {
                    Firstname = request.Firstname,
                    Lastname = request.Lastname,
                    Email = request.Email.ToLower(),
                    Password = BCrypt.Net.BCrypt.HashPassword(autoGeneratedPassword),
                    Role = request.Role.ToLower(),
                    isMFAEnabled = false,
                    isFirstSignIn = true,
                    isMFAVerified = false,
                    Active = true,
                    CreatedAt = DateTime.Now.AddHours(2),
                    UpdatedAt = DateTime.Now.AddHours(2)
                };

                var isUserAdded = await _userRepo.AddUser(user);

                if (isUserAdded == null)
                {
                    return BadRequest(new { Message = "Could not add the user" });
                }

                var baseUrl = Environment.GetEnvironmentVariable("FrontEndBaseUrl")!;
                var url = $"{baseUrl}/auth";
                var path = $"./Templates/user-created.html";
                var template = System.IO.File.ReadAllText(path).Replace("\n", "");

                template = template.Replace("{{NAME}}", user.Firstname)
                                   .Replace("{{PASSWORD}}", autoGeneratedPassword)
                                   .Replace("{{LOGIN_LINK}}", url);
                List<string> receipient = new List<string>{ user.Email };

                string response = await _emailService.SendTemplateEmail(receipient, "Account Created", template);

                return Ok(new { Message = "User added successfully" });

            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error in the controller while trying to add user");
                return StatusCode(500, new { Message = "Encountered an error" });
            }
        }
        #endregion

        #region [ Add Guardian ]
        [AllowAnonymous]
        [HttpPost("add-guardian")]
        public async Task<ActionResult> AddGuardian(AddGuardian request)
        {

            try
            {
                var roles = new List<string>() { "staff", "admin", "guardian" };

                var userExists = await _userRepo.GetUserByEmail(request.Email);

                if (userExists != null)
                {
                    return Conflict(new { Message = "User already exists" });
                }

                if (!_passwordHelper.IsPasswordValid(request.Password))
                {
                    return BadRequest(new
                    {
                        Message = "Your password must be 8 characters long or more, " +
                        "contain at least 1 number and special character"
                    });
                }

                User user = new User
                {
                    Firstname = request.Firstname,
                    Lastname = request.Lastname,
                    Email = request.Email.ToLower(),
                    Password = request.Password,
                    Role = "guardian",
                    isMFAEnabled = false,
                    isFirstSignIn = true,
                    isMFAVerified = false,
                    Active = true,
                    CreatedAt = DateTime.Now.AddHours(2),
                    UpdatedAt = DateTime.Now.AddHours(2)
                };

                var isUserAdded = await _userRepo.AddUser(user);

                if (isUserAdded == null)
                {
                    return BadRequest(new { Message = "Could not add the user" });
                }

                var baseUrl = Environment.GetEnvironmentVariable("FrontEndBaseUrl")!;
                var url = $"{baseUrl}/auth";
                var path = $"./Templates/user-created.html";
                var template = System.IO.File.ReadAllText(path).Replace("\n", "");

                template = template.Replace("{{NAME}}", user.Firstname)
                                   .Replace("{{PASSWORD}}", request.Password)
                                   .Replace("{{LOGIN_LINK}}", url);
                List<string> receipient = new List<string> { user.Email };

                string response = await _emailService.SendTemplateEmail(receipient, "Account Created", template);

                return Ok(new { Message = "User added successfully" });

            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error in the controller while trying to add user");
                return StatusCode(500, new { Message = "Encountered an error" });
            }
        }
        #endregion

        #region [ Get Users ]
        [Authorize(Roles = "admin,staff")]
        [HttpGet]
        public async Task<ActionResult<List<UserDTO>>> GetUsers()
        {
            try
            {
                var tokenType = User.Claims.FirstOrDefault(c => c.Type == "TokenType")?.Value;

                if (tokenType != "access-token")
                {
                    return Unauthorized(new { Message = "Invalid token" });
                }

                var users = await _userRepo.GetAllUsers();

                var usersDTO = users.Select(x => new UserDTO
                {
                    Email = x.Email,
                    Firstname = x.Firstname,
                    Lastname = x.Lastname,
                    Role = x.Role,
                    Id = x.Id,
                    Active = x.Active,
                    isMFAEnabled = x.isMFAEnabled,
                    CreatedAt = x.CreatedAt,
                    UpdatedAt = x.UpdatedAt
                });

                return Ok(usersDTO);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error in the Users Controller while trying to get all users");
                return StatusCode(500, new { Message = "Encountered an error" });
            }
        }
        #endregion

        #region [ Get User By Id ]
        [Authorize(Roles = "admin,staff")]
        [HttpGet("{id:length(24)}")]
        public async Task<ActionResult<UserDTO>> GetUserById(string id)
        {
            try
            {
                var tokenType = User.Claims.FirstOrDefault(c => c.Type == "TokenType")?.Value;

                if (tokenType != "access-token")
                {
                    return Unauthorized(new { Message = "Invalid token" });
                }

                var user = await _userRepo.GetUserById(id);

                if (user == null)
                {
                    return NotFound(new { Message = "User does not exist" });
                }

                var userDTO = new UserDTO()
                {
                    Email = user.Email,
                    Firstname = user.Firstname,
                    Lastname = user.Lastname,
                    Role = user.Role,
                    Id = user.Id,
                    Active = user.Active,
                    isMFAEnabled = user.isMFAEnabled,
                    CreatedAt = user.CreatedAt,
                    UpdatedAt = user.UpdatedAt
                };

                return Ok(userDTO);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error in the Users Controller while trying to get user by id");
                return StatusCode(500, new { Message = "Encountered an error" });
            }
        }
        #endregion

        #region [ Update Staff ]
        [Authorize(Roles = "admin")]
        [HttpPut("staff-update/{id:length(24)}")]
        public async Task<ActionResult<UpdateResult>> UpdateStaff(string id, StaffUpdate payload)
        {
            try
            {
                var validRoles = new List<string>() { "user", "admin" };
                var tokenType = User.Claims.FirstOrDefault(c => c.Type == "TokenType")?.Value;

                if (tokenType != "access-token")
                {
                    return Unauthorized(new { Message = "Invalid token" });
                }

                var user = await _userRepo.GetUserById(id);

                if (user == null)
                {
                    return NotFound(new { Message = "User does not exist" });
                }

                if (!string.IsNullOrEmpty(payload.Role))
                {
                    if (!validRoles.Contains(payload.Role.ToLower()))
                    {
                        return BadRequest(new { Message = "There is no such Role" });
                    }
                }


                if (!string.IsNullOrEmpty(payload.Email))
                {
                    var emailExists = await _userRepo.GetUserByEmail(payload.Email.ToLower());

                    if (emailExists != null && id != emailExists.Id)
                    {
                        return Conflict(new { Message = "Email belongs to a different user" });
                    }

                    if (emailExists == null && user.isMFAEnabled == true)
                    {
                        UpdateMfaFieldsModel mfaFieldsModel = new UpdateMfaFieldsModel()
                        {
                            isFirstSignIn = true,
                            isMFAVerified = false,
                            ManualEntryCode = null,
                            userId = user.Id,
                            MFAKey = null,
                            QrCodeUrl = null,
                        };

                        var mfaUpdated = await _userRepo.UpdateMFAfields(mfaFieldsModel);

                        if (mfaUpdated.IsAcknowledged == false)
                        {
                            _logger.LogError("Could not update mfa fields");
                            return BadRequest(new { Message = "Could not update user" });
                        }
                    }
                }


                var isUpdated = await _userRepo.UpdateStaff(id, payload);

                if (isUpdated.IsAcknowledged == false)
                {
                    return BadRequest(new { Message = "Could not update user" });
                }

                return Ok(new { Messagee = "User updated successfully" });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error in the Users Controller while trying to update user");
                return StatusCode(500, new { Message = "Encountered an error" });
            }
        }
        #endregion

        #region [ Update User ]
        [HttpPut("update-user/{id:length(24)}")]
        public async Task<ActionResult<UpdateResult>> UpdateUser(string id, UserUpdate payload)
        {
            try
            {
                var tokenType = User.Claims.FirstOrDefault(c => c.Type == "TokenType")?.Value;
                var tokenUserId = User?.FindFirstValue(ClaimTypes.Sid)?.ToString();
                var tokenUserEmail = User?.FindFirstValue(ClaimTypes.Email)?.ToString();

                if (tokenType != "access-token")
                {
                    return Unauthorized(new { Message = "Invalid token" });
                }

                var user = await _userRepo.GetUserById(id);

                if (user == null)
                {
                    return NotFound(new { Message = "User does not exist" });
                }

                if (tokenType != "access-token" || user.Email != tokenUserEmail)
                {
                    return Unauthorized(new { Message = "Unauthorized User/Invalid token" });
                }


                if (!string.IsNullOrEmpty(payload.Email))
                {
                    var emailExists = await _userRepo.GetUserByEmail(payload.Email.ToLower());

                    if (emailExists != null && id != emailExists.Id)
                    {
                        return Conflict(new { Message = "Email belongs to a different user" });
                    }

                    if (emailExists == null && user.isMFAEnabled == true)
                    {
                        UpdateMfaFieldsModel mfaFieldsModel = new UpdateMfaFieldsModel()
                        {
                            isFirstSignIn = true,
                            isMFAVerified = false,
                            ManualEntryCode = null,
                            userId = user.Id,
                            MFAKey = null,
                            QrCodeUrl = null,
                        };

                        var mfaUpdated = await _userRepo.UpdateMFAfields(mfaFieldsModel);

                        if (mfaUpdated.IsAcknowledged == false)
                        {
                            _logger.LogError("Could not update mfa fields");
                            return BadRequest(new { Message = "Could not update user" });
                        }
                    }
                }


                var isUpdated = await _userRepo.UpdateUser(id, payload);

                if (isUpdated.IsAcknowledged == false)
                {
                    return BadRequest(new { Message = "Could not update user" });
                }

                return Ok(new { Messagee = "User updated successfully" });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error in the Users Controller while trying to update user");
                return StatusCode(500, new { Message = "Encountered an error" });
            }
        }
        #endregion

        #region [ Update MFA ]
        [HttpPatch("enable-mfa/{id:length(24)}")]
        public async Task<ActionResult<UpdateResult>> EnableMFA(string id, EnableMFAModel payload)
        {
            try
            {
                var validRoles = new List<string>() { "user", "admin" };
                var tokenType = User.Claims.FirstOrDefault(c => c.Type == "TokenType")?.Value;
                var tokenUserId = User?.FindFirstValue(ClaimTypes.Sid)?.ToString();
                var tokenUserEmail = User?.FindFirstValue(ClaimTypes.Email)?.ToString();
                
                var user = await _userRepo.GetUserById(id);

                if (tokenType != "access-token" || user.Email != tokenUserEmail)
                {
                    return Unauthorized(new { Message = "Unauthorized User/Invalid token" });
                }

                if (user == null)
                {
                    return NotFound(new { Message = "User does not exist" });
                }

                var userExists = await _userRepo.GetUserByEmail(user.Email.ToLower());

                if (payload.enable == false)
                {
                    UpdateMfaFieldsModel mfaFieldsModel = new UpdateMfaFieldsModel()
                    {
                        isFirstSignIn = true,
                        isMFAVerified = false,
                        ManualEntryCode = null,
                        userId = user.Id,
                        MFAKey = null,
                        QrCodeUrl = null,
                    };

                    var mfaUpdated = await _userRepo.UpdateMFAfields(mfaFieldsModel);

                    if (mfaUpdated.IsAcknowledged == false)
                    {
                        _logger.LogError("Could not update mfa fields");
                        return BadRequest(new { Message = "Could not update user" });
                    }
                }

                var isUpdated = await _userRepo.EnableMFA(id, payload.enable);

                if (isUpdated.IsAcknowledged == false)
                {
                    return BadRequest(new { Message = "Could not update MFA" });
                }

                return Ok(new { Messagee = "MFA is updated successfully" });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error in the Users Controller while trying to update MFA");
                return StatusCode(500, new { Message = "Encountered an error" });
            }
        }
        #endregion

        #region [ Delete User ]
        [Authorize(Roles = "admin")]
        [HttpDelete("{id:length(24)}")]
        public async Task<ActionResult<DeleteResult>> DeleteUser(string id)
        {
            try
            {
                var tokenType = User.Claims.FirstOrDefault(c => c.Type == "TokenType")?.Value;

                if (tokenType != "access-token")
                {
                    return Unauthorized(new { Message = "Invalid token" });
                }

                var user = await _userRepo.GetUserById(id);

                if (user == null)
                {
                    return NotFound(new { Message = "User Id does not exist" });
                }

                var isDeleted = await _userRepo.DeleteUser(id);

                if (isDeleted.IsAcknowledged == false)
                {
                    return BadRequest(new { Message = "Could not delete user" });
                }

                return Ok(new { Message = "User deleted successfully" });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error in the Users Controller while trying to delete user");
                return StatusCode(500, new { Message = "Encountered an error" });
            }
        }
        #endregion

    }
}
